export type LanguageCode = 'en' | 'hi' | 'kn';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिंदी' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ' },
];

type TranslationKeys = {
  [key: string]: string;
};

type Translations = {
  [key in LanguageCode]: TranslationKeys;
};

export const translations: Translations = {
  en: {
    // App
    appName: 'MedQ+',
    appTagline: 'Find Trusted Doctors Near You',

    // Navigation
    home: 'Home',
    bookings: 'Bookings',
    profile: 'Profile',
    nearMe: 'Near Me',

    // Home
    currentLocation: 'Current Location',
    changeLocation: 'Change',
    searchPlaceholder: 'Search doctor, hospital or disease...',
    categories: 'Categories',
    topDoctors: 'Top Doctors',
    nearbyHospitals: 'Nearby Hospitals',
    seeAll: 'See All',

    // Categories
    generalPhysician: 'General Physician',
    pediatrician: 'Pediatrician',
    orthopedic: 'Orthopedic',
    dentist: 'Dentist',
    eyeSpecialist: 'Eye Specialist',
    skinSpecialist: 'Skin Specialist',
    heartSpecialist: 'Heart Specialist',
    neuroSpecialist: 'Brain & Nerve',
    gynecologist: 'Gynecologist',
    dermatologist: 'Dermatologist',

    // Doctor Card
    yearsExp: 'yrs exp',
    verified: '✔ Verified Doctor',
    patientsServed: 'patients served',
    viewProfile: 'View Profile',
    bookNow: 'Book Now',

    // Doctor Profile
    aboutDoctor: 'About Doctor',
    education: 'Education',
    specialTraining: 'Special Training',
    hospitalAffiliation: 'Hospital Affiliation',
    languagesSpoken: 'Languages Spoken',
    trustIndicators: 'Why Trust This Doctor?',
    treatingPatients: 'years treating patients',
    profileStrength: 'Profile Strength',
    strongProfileHelps: 'Strong profile helps patients trust you',
    photoAdded: 'Photo Added',
    educationFilled: 'Education Filled',
    specializationFilled: 'Specialization Filled',
    experienceFilled: 'Experience Filled',
    bookAppointment: 'Book Appointment',

    // Booking
    selectDate: 'Select Date',
    selectTime: 'Select Time Slot',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    confirmBooking: 'Confirm Booking',
    platformFee: 'Platform Fee',
    consultationFee: 'Doctor consultation fee is paid at clinic',
    payAtClinic: 'Pay at Clinic (Cash)',
    payPlatformFee: 'Pay ₹20 Platform Fee',
    bookingConfirmed: 'Booking Confirmed!',
    bookingSuccess: 'Your appointment is booked successfully',
    yourToken: 'Your Token Number',
    trackToken: 'Track Live Token',
    goHome: 'Go to Home',

    // Token Tracker
    liveTokenTracker: 'Live Token Tracker',
    currentToken: 'CURRENT TOKEN',
    yourTokenNumber: 'YOUR TOKEN',
    estimatedWait: 'Estimated Wait',
    minutes: 'minutes',
    tokensBefore: 'tokens before you',
    pleaseWait: 'Please wait, your turn is coming!',
    yourTurn: 'It\'s your turn!',

    // Near Me
    nearbyDoctors: 'Nearby Doctors & Hospitals',

    // Profile
    myProfile: 'My Profile',
    editProfile: 'Edit Profile',
    fullName: 'Full Name',
    age: 'Age',
    phone: 'Phone Number',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    myBookings: 'My Bookings',
    language: 'Language',
    helpSupport: 'Help & Support',
    logout: 'Logout',
    save: 'Save',
    cancel: 'Cancel',

    // Auth
    welcome: 'Welcome to MedQ+',
    loginSubtitle: 'Find trusted doctors near you',
    enterPhone: 'Enter your phone number',
    enterOTP: 'Enter OTP',
    sendOTP: 'Send OTP',
    verifyOTP: 'Verify OTP',
    register: 'Register',
    login: 'Login',
    name: 'Your Name',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account? Login',
    dontHaveAccount: 'Don\'t have an account? Register',

    // Booking list
    upcomingBookings: 'Upcoming Bookings',
    pastBookings: 'Past Bookings',
    noBookings: 'No bookings yet',
    noBookingsDesc: 'Book your first doctor appointment now!',
    findDoctor: 'Find a Doctor',
    today: 'Today',
    tomorrow: 'Tomorrow',
    confirmed: 'Confirmed',
    completed: 'Completed',
    cancelled: 'Cancelled',

    // Search tab
    search: 'Search',
    searchDoctorDisease: 'Search by disease, doctor or hospital...',
    searchHint: 'Try: Fever, Knee pain, Dentist...',
    browseByCategory: 'Browse by Category',
    searchResults: 'Search Results',
    noResults: 'No doctors found',
    noResultsDesc: 'Try a different search or browse categories',
    doctorsFound: 'doctors found',

    // Home new
    famousDoctors: 'Famous Doctors',
    welcomeMsg: 'Your Health, Our Priority',
    detectingLocation: 'Detecting your location...',
    categoryDoctors: 'Doctors',

    // Location Picker
    selectLocation: 'Select Location',
    searchLocationPlaceholder: 'Search area, city or pincode...',
    useCurrentLocation: 'Use Current Location',
    usingGPS: 'Using GPS',
    locationsFound: 'locations found',
    noLocationsFound: 'No locations found',
    tryDifferentSearch: 'Try a different area name or pincode',
    recentLocations: 'Recent Locations',
    popularCities: 'Popular Cities',
    allAreas: 'All Areas',

    // Payment
    paymentDetails: 'Payment Details',
    total: 'Total',
    free: 'FREE',
  },
  hi: {
    appName: 'MedQ+',
    appTagline: 'अपने पास विश्वसनीय डॉक्टर खोजें',

    home: 'होम',
    bookings: 'बुकिंग',
    profile: 'प्रोफ़ाइल',
    nearMe: 'मेरे पास',

    currentLocation: 'वर्तमान स्थान',
    changeLocation: 'बदलें',
    searchPlaceholder: 'डॉक्टर, अस्पताल या बीमारी खोजें...',
    categories: 'श्रेणियाँ',
    topDoctors: 'शीर्ष डॉक्टर',
    nearbyHospitals: 'पास के अस्पताल',
    seeAll: 'सभी देखें',

    generalPhysician: 'सामान्य चिकित्सक',
    pediatrician: 'बाल रोग विशेषज्ञ',
    orthopedic: 'हड्डी रोग विशेषज्ञ',
    dentist: 'दंत चिकित्सक',
    eyeSpecialist: 'नेत्र विशेषज्ञ',
    skinSpecialist: 'त्वचा विशेषज्ञ',
    heartSpecialist: 'हृदय विशेषज्ञ',
    neuroSpecialist: 'मस्तिष्क और तंत्रिका',
    gynecologist: 'स्त्री रोग विशेषज्ञ',
    dermatologist: 'त्वचा रोग विशेषज्ञ',

    yearsExp: 'साल अनुभव',
    verified: '✔ सत्यापित डॉक्टर',
    patientsServed: 'मरीज़ देखे गए',
    viewProfile: 'प्रोफ़ाइल देखें',
    bookNow: 'अभी बुक करें',

    aboutDoctor: 'डॉक्टर के बारे में',
    education: 'शिक्षा',
    specialTraining: 'विशेष प्रशिक्षण',
    hospitalAffiliation: 'अस्पताल संबद्धता',
    languagesSpoken: 'बोली जाने वाली भाषाएँ',
    trustIndicators: 'इस डॉक्टर पर भरोसा क्यों करें?',
    treatingPatients: 'साल से मरीज़ों का इलाज',
    profileStrength: 'प्रोफ़ाइल की ताकत',
    strongProfileHelps: 'मज़बूत प्रोफ़ाइल मरीज़ों का भरोसा बढ़ाती है',
    photoAdded: 'फ़ोटो जोड़ी गई',
    educationFilled: 'शिक्षा भरी गई',
    specializationFilled: 'विशेषज्ञता भरी गई',
    experienceFilled: 'अनुभव भरा गया',
    bookAppointment: 'अपॉइंटमेंट बुक करें',

    selectDate: 'तारीख़ चुनें',
    selectTime: 'समय चुनें',
    morning: 'सुबह',
    afternoon: 'दोपहर',
    evening: 'शाम',
    confirmBooking: 'बुकिंग पक्की करें',
    platformFee: 'प्लेटफ़ॉर्म शुल्क',
    consultationFee: 'डॉक्टर की फ़ीस क्लिनिक में दें',
    payAtClinic: 'क्लिनिक में भुगतान (नकद)',
    payPlatformFee: '₹20 प्लेटफ़ॉर्म शुल्क दें',
    bookingConfirmed: 'बुकिंग पक्की हो गई!',
    bookingSuccess: 'आपकी अपॉइंटमेंट सफलतापूर्वक बुक हो गई',
    yourToken: 'आपका टोकन नंबर',
    trackToken: 'लाइव टोकन ट्रैक करें',
    goHome: 'होम पर जाएँ',

    liveTokenTracker: 'लाइव टोकन ट्रैकर',
    currentToken: 'वर्तमान टोकन',
    yourTokenNumber: 'आपका टोकन',
    estimatedWait: 'अनुमानित प्रतीक्षा',
    minutes: 'मिनट',
    tokensBefore: 'टोकन आपसे पहले',
    pleaseWait: 'कृपया प्रतीक्षा करें, आपकी बारी आ रही है!',
    yourTurn: 'आपकी बारी आ गई!',

    nearbyDoctors: 'पास के डॉक्टर और अस्पताल',

    myProfile: 'मेरी प्रोफ़ाइल',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    fullName: 'पूरा नाम',
    age: 'उम्र',
    phone: 'फ़ोन नंबर',
    gender: 'लिंग',
    male: 'पुरुष',
    female: 'महिला',
    other: 'अन्य',
    myBookings: 'मेरी बुकिंग',
    language: 'भाषा',
    helpSupport: 'सहायता',
    logout: 'लॉगआउट',
    save: 'सहेजें',
    cancel: 'रद्द करें',

    welcome: 'MedQ+ में आपका स्वागत है',
    loginSubtitle: 'अपने पास विश्वसनीय डॉक्टर खोजें',
    enterPhone: 'अपना फ़ोन नंबर डालें',
    enterOTP: 'OTP डालें',
    sendOTP: 'OTP भेजें',
    verifyOTP: 'OTP सत्यापित करें',
    register: 'रजिस्टर',
    login: 'लॉगिन',
    name: 'आपका नाम',
    createAccount: 'खाता बनाएँ',
    alreadyHaveAccount: 'पहले से खाता है? लॉगिन करें',
    dontHaveAccount: 'खाता नहीं है? रजिस्टर करें',

    upcomingBookings: 'आगामी बुकिंग',
    pastBookings: 'पिछली बुकिंग',
    noBookings: 'कोई बुकिंग नहीं',
    noBookingsDesc: 'अपनी पहली अपॉइंटमेंट अभी बुक करें!',
    findDoctor: 'डॉक्टर खोजें',
    today: 'आज',
    tomorrow: 'कल',
    confirmed: 'पक्की',
    completed: 'पूरी',
    cancelled: 'रद्द',

    paymentDetails: 'भुगतान विवरण',
    total: 'कुल',
    free: 'मुफ़्त',

    // Location Picker
    selectLocation: 'स्थान चुनें',
    searchLocationPlaceholder: 'क्षेत्र, शहर या पिनकोड खोजें...',
    useCurrentLocation: 'वर्तमान स्थान उपयोग करें',
    usingGPS: 'GPS का उपयोग करके',
    locationsFound: 'स्थान मिले',
    noLocationsFound: 'कोई स्थान नहीं मिला',
    tryDifferentSearch: 'दूसरा क्षेत्र नाम या पिनकोड आज़माएँ',
    recentLocations: 'हाल के स्थान',
    popularCities: 'लोकप्रिय शहर',
    allAreas: 'सभी क्षेत्र',

    search: 'खोजें',
    searchDoctorDisease: 'बीमारी, डॉक्टर या अस्पताल खोजें...',
    searchHint: 'बुखार, घुटने का दर्द, दंत चिकित्सक...',
    browseByCategory: 'श्रेणी से खोजें',
    searchResults: 'खोज परिणाम',
    noResults: 'कोई डॉक्टर नहीं मिला',
    noResultsDesc: 'दूसरी खोज करें या श्रेणी चुनें',
    doctorsFound: 'डॉक्टर मिले',
    famousDoctors: 'प्रसिद्ध डॉक्टर',
    welcomeMsg: 'आपकी सेहत, हमारी प्राथमिकता',
    detectingLocation: 'आपका स्थान खोज रहे हैं...',
    categoryDoctors: 'डॉक्टर',
  },
  kn: {
    appName: 'MedQ+',
    appTagline: 'ನಿಮ್ಮ ಹತ್ತಿರದ ನಂಬಿಗಸ್ಥ ವೈದ್ಯರನ್ನು ಹುಡುಕಿ',

    home: 'ಮುಖಪುಟ',
    bookings: 'ಬುಕಿಂಗ್',
    profile: 'ಪ್ರೊಫೈಲ್',
    nearMe: 'ನನ್ನ ಹತ್ತಿರ',

    currentLocation: 'ಪ್ರಸ್ತುತ ಸ್ಥಳ',
    changeLocation: 'ಬದಲಾಯಿಸಿ',
    searchPlaceholder: 'ವೈದ್ಯ, ಆಸ್ಪತ್ರೆ ಅಥವಾ ರೋಗ ಹುಡುಕಿ...',
    categories: 'ವಿಭಾಗಗಳು',
    topDoctors: 'ಉತ್ತಮ ವೈದ್ಯರು',
    nearbyHospitals: 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು',
    seeAll: 'ಎಲ್ಲಾ ನೋಡಿ',

    generalPhysician: 'ಸಾಮಾನ್ಯ ವೈದ್ಯ',
    pediatrician: 'ಮಕ್ಕಳ ವೈದ್ಯ',
    orthopedic: 'ಮೂಳೆ ವೈದ್ಯ',
    dentist: 'ಹಲ್ಲಿನ ವೈದ್ಯ',
    eyeSpecialist: 'ಕಣ್ಣಿನ ವೈದ್ಯ',
    skinSpecialist: 'ಚರ್ಮ ವೈದ್ಯ',
    heartSpecialist: 'ಹೃದಯ ವೈದ್ಯ',
    neuroSpecialist: 'ಮೆದುಳು ಮತ್ತು ನರ',
    gynecologist: 'ಸ್ತ್ರೀ ರೋಗ ತಜ್ಞ',
    dermatologist: 'ಚರ್ಮ ರೋಗ ತಜ್ಞ',

    yearsExp: 'ವರ್ಷ ಅನುಭವ',
    verified: '✔ ಪರಿಶೀಲಿತ ವೈದ್ಯ',
    patientsServed: 'ರೋಗಿಗಳಿಗೆ ಚಿಕಿತ್ಸೆ',
    viewProfile: 'ಪ್ರೊಫೈಲ್ ನೋಡಿ',
    bookNow: 'ಈಗ ಬುಕ್ ಮಾಡಿ',

    aboutDoctor: 'ವೈದ್ಯರ ಬಗ್ಗೆ',
    education: 'ಶಿಕ್ಷಣ',
    specialTraining: 'ವಿಶೇಷ ತರಬೇತಿ',
    hospitalAffiliation: 'ಆಸ್ಪತ್ರೆ ಸಂಬಂಧ',
    languagesSpoken: 'ಮಾತನಾಡುವ ಭಾಷೆಗಳು',
    trustIndicators: 'ಈ ವೈದ್ಯರನ್ನು ಏಕೆ ನಂಬಬೇಕು?',
    treatingPatients: 'ವರ್ಷಗಳ ಚಿಕಿತ್ಸಾ ಅನುಭವ',
    profileStrength: 'ಪ್ರೊಫೈಲ್ ಬಲ',
    strongProfileHelps: 'ಬಲವಾದ ಪ್ರೊಫೈಲ್ ರೋಗಿಗಳ ನಂಬಿಕೆ ಹೆಚ್ಚಿಸುತ್ತದೆ',
    photoAdded: 'ಫೋಟೋ ಸೇರಿಸಲಾಗಿದೆ',
    educationFilled: 'ಶಿಕ್ಷಣ ಭರ್ತಿ',
    specializationFilled: 'ವಿಶೇಷತೆ ಭರ್ತಿ',
    experienceFilled: 'ಅನುಭವ ಭರ್ತಿ',
    bookAppointment: 'ಅಪಾಯಿಂಟ್ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ',

    selectDate: 'ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ',
    selectTime: 'ಸಮಯ ಆಯ್ಕೆಮಾಡಿ',
    morning: 'ಬೆಳಿಗ್ಗೆ',
    afternoon: 'ಮಧ್ಯಾಹ್ನ',
    evening: 'ಸಂಜೆ',
    confirmBooking: 'ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಿ',
    platformFee: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ',
    consultationFee: 'ವೈದ್ಯರ ಶುಲ್ಕ ಕ್ಲಿನಿಕ್‌ನಲ್ಲಿ ಪಾವತಿಸಿ',
    payAtClinic: 'ಕ್ಲಿನಿಕ್‌ನಲ್ಲಿ ಪಾವತಿ (ನಗದು)',
    payPlatformFee: '₹20 ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ',
    bookingConfirmed: 'ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಲಾಗಿದೆ!',
    bookingSuccess: 'ನಿಮ್ಮ ಅಪಾಯಿಂಟ್ಮೆಂಟ್ ಯಶಸ್ವಿಯಾಗಿ ಬುಕ್ ಆಗಿದೆ',
    yourToken: 'ನಿಮ್ಮ ಟೋಕನ್ ಸಂಖ್ಯೆ',
    trackToken: 'ಲೈವ್ ಟೋಕನ್ ಟ್ರ್ಯಾಕ್',
    goHome: 'ಮುಖಪುಟಕ್ಕೆ ಹೋಗಿ',

    liveTokenTracker: 'ಲೈವ್ ಟೋಕನ್ ಟ್ರ್ಯಾಕರ್',
    currentToken: 'ಪ್ರಸ್ತುತ ಟೋಕನ್',
    yourTokenNumber: 'ನಿಮ್ಮ ಟೋಕನ್',
    estimatedWait: 'ಅಂದಾಜು ಕಾಯುವ ಸಮಯ',
    minutes: 'ನಿಮಿಷ',
    tokensBefore: 'ಟೋಕನ್‌ಗಳು ನಿಮ್ಮ ಮುಂದೆ',
    pleaseWait: 'ದಯವಿಟ್ಟು ಕಾಯಿರಿ, ನಿಮ್ಮ ಸರದಿ ಬರುತ್ತಿದೆ!',
    yourTurn: 'ನಿಮ್ಮ ಸರದಿ ಬಂದಿದೆ!',

    nearbyDoctors: 'ಹತ್ತಿರದ ವೈದ್ಯರು ಮತ್ತು ಆಸ್ಪತ್ರೆಗಳು',

    myProfile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    editProfile: 'ಪ್ರೊಫೈಲ್ ಬದಲಾಯಿಸಿ',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    age: 'ವಯಸ್ಸು',
    phone: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    gender: 'ಲಿಂಗ',
    male: 'ಪುರುಷ',
    female: 'ಮಹಿಳೆ',
    other: 'ಇತರ',
    myBookings: 'ನನ್ನ ಬುಕಿಂಗ್',
    language: 'ಭಾಷೆ',
    helpSupport: 'ಸಹಾಯ',
    logout: 'ಲಾಗ್‌ಔಟ್',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದು',

    welcome: 'MedQ+ ಗೆ ಸುಸ್ವಾಗತ',
    loginSubtitle: 'ನಿಮ್ಮ ಹತ್ತಿರದ ನಂಬಿಗಸ್ಥ ವೈದ್ಯರನ್ನು ಹುಡುಕಿ',
    enterPhone: 'ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    enterOTP: 'OTP ನಮೂದಿಸಿ',
    sendOTP: 'OTP ಕಳುಹಿಸಿ',
    verifyOTP: 'OTP ಪರಿಶೀಲಿಸಿ',
    register: 'ನೋಂದಣಿ',
    login: 'ಲಾಗಿನ್',
    name: 'ನಿಮ್ಮ ಹೆಸರು',
    createAccount: 'ಖಾತೆ ರಚಿಸಿ',
    alreadyHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್',
    dontHaveAccount: 'ಖಾತೆ ಇಲ್ಲವೇ? ನೋಂದಣಿ',

    upcomingBookings: 'ಮುಂಬರುವ ಬುಕಿಂಗ್',
    pastBookings: 'ಹಿಂದಿನ ಬುಕಿಂಗ್',
    noBookings: 'ಬುಕಿಂಗ್ ಇಲ್ಲ',
    noBookingsDesc: 'ನಿಮ್ಮ ಮೊದಲ ಅಪಾಯಿಂಟ್ಮೆಂಟ್ ಈಗ ಬುಕ್ ಮಾಡಿ!',
    findDoctor: 'ವೈದ್ಯರನ್ನು ಹುಡುಕಿ',
    today: 'ಇಂದು',
    tomorrow: 'ನಾಳೆ',
    confirmed: 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    completed: 'ಪೂರ್ಣ',
    cancelled: 'ರದ್ದು',

    paymentDetails: 'ಪಾವತಿ ವಿವರ',
    total: 'ಒಟ್ಟು',
    free: 'ಉಚಿತ',

    // Location Picker
    selectLocation: 'ಸ್ಥಳ ಆಯ್ಕೆಮಾಡಿ',
    searchLocationPlaceholder: 'ಪ್ರದೇಶ, ನಗರ ಅಥವಾ ಪಿನ್‌ಕೋಡ್ ಹುಡುಕಿ...',
    useCurrentLocation: 'ಪ್ರಸ್ತುತ ಸ್ಥಳ ಬಳಸಿ',
    usingGPS: 'GPS ಬಳಸಿ',
    locationsFound: 'ಸ್ಥಳಗಳು ಕಂಡುಬಂದವು',
    noLocationsFound: 'ಸ್ಥಳಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    tryDifferentSearch: 'ಬೇರೆ ಪ್ರದೇಶ ಹೆಸರು ಅಥವಾ ಪಿನ್‌ಕೋಡ್ ಪ್ರಯತ್ನಿಸಿ',
    recentLocations: 'ಇತ್ತೀಚಿನ ಸ್ಥಳಗಳು',
    popularCities: 'ಜನಪ್ರಿಯ ನಗರಗಳು',
    allAreas: 'ಎಲ್ಲಾ ಪ್ರದೇಶಗಳು',

    search: 'ಹುಡುಕಿ',
    searchDoctorDisease: 'ರೋಗ, ವೈದ್ಯ ಅಥವಾ ಆಸ್ಪತ್ರೆ ಹುಡುಕಿ...',
    searchHint: 'ಜ್ವರ, ಮೊಣಕಾಲು ನೋವು, ಹಲ್ಲಿನ ವೈದ್ಯ...',
    browseByCategory: 'ವಿಭಾಗದ ಮೂಲಕ ಹುಡುಕಿ',
    searchResults: 'ಹುಡುಕಾಟ ಫಲಿತಾಂಶ',
    noResults: 'ವೈದ್ಯರು ಕಂಡುಬಂದಿಲ್ಲ',
    noResultsDesc: 'ಬೇರೆ ಹುಡುಕಾಟ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ವಿಭಾಗ ಆಯ್ಕೆಮಾಡಿ',
    doctorsFound: 'ವೈದ್ಯರು ಕಂಡುಬಂದರು',
    famousDoctors: 'ಪ್ರಸಿದ್ಧ ವೈದ್ಯರು',
    welcomeMsg: 'ನಿಮ್ಮ ಆರೋಗ್ಯ, ನಮ್ಮ ಆದ್ಯತೆ',
    detectingLocation: 'ನಿಮ್ಮ ಸ್ಥಳ ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    categoryDoctors: 'ವೈದ್ಯರು',
  },
};

